USE [master]

/****** Object:  Database [FileUploader]    Script Date: 7/12/2018 6:28:16 PM ******/
CREATE DATABASE [FileUploader]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FileUploader', FILENAME = N'D:\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\FileUploader.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FileUploader_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\FileUploader_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )

ALTER DATABASE [FileUploader] SET COMPATIBILITY_LEVEL = 130

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FileUploader].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [FileUploader] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [FileUploader] SET ANSI_NULLS OFF 

ALTER DATABASE [FileUploader] SET ANSI_PADDING OFF 

ALTER DATABASE [FileUploader] SET ANSI_WARNINGS OFF 

ALTER DATABASE [FileUploader] SET ARITHABORT OFF 

ALTER DATABASE [FileUploader] SET AUTO_CLOSE OFF 

ALTER DATABASE [FileUploader] SET AUTO_SHRINK OFF 

ALTER DATABASE [FileUploader] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [FileUploader] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [FileUploader] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [FileUploader] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [FileUploader] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [FileUploader] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [FileUploader] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [FileUploader] SET  ENABLE_BROKER 

ALTER DATABASE [FileUploader] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [FileUploader] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [FileUploader] SET TRUSTWORTHY OFF 

ALTER DATABASE [FileUploader] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [FileUploader] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [FileUploader] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [FileUploader] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [FileUploader] SET RECOVERY FULL 

ALTER DATABASE [FileUploader] SET  MULTI_USER 

ALTER DATABASE [FileUploader] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [FileUploader] SET DB_CHAINING OFF 

ALTER DATABASE [FileUploader] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [FileUploader] SET TARGET_RECOVERY_TIME = 60 SECONDS 

ALTER DATABASE [FileUploader] SET DELAYED_DURABILITY = DISABLED 

EXEC sys.sp_db_vardecimal_storage_format N'FileUploader', N'ON'

ALTER DATABASE [FileUploader] SET QUERY_STORE = OFF

USE [FileUploader]

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;

USE [FileUploader]

/****** Object:  User [NT AUTHORITY\NETWORK SERVICE]    Script Date: 7/12/2018 6:28:16 PM ******/
CREATE USER [NT AUTHORITY\NETWORK SERVICE] FOR LOGIN [NT AUTHORITY\NETWORK SERVICE] WITH DEFAULT_SCHEMA=[dbo]

ALTER ROLE [db_datareader] ADD MEMBER [NT AUTHORITY\NETWORK SERVICE]

ALTER ROLE [db_datawriter] ADD MEMBER [NT AUTHORITY\NETWORK SERVICE]

/****** Object:  Table [dbo].[Files]    Script Date: 7/12/2018 6:28:16 PM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Files](
	[FilePK] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](max) NOT NULL,
	[TotalSize] [float] NOT NULL,
	[IsComplete] [bit] NOT NULL,
	[Path] [varchar](max) NULL,
	[FileID] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Files] PRIMARY KEY CLUSTERED 
(
	[FilePK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

/****** Object:  Table [dbo].[TempFiles]    Script Date: 7/12/2018 6:28:17 PM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TempFiles](
	[TempFilePK] [int] IDENTITY(1,1) NOT NULL,
	[FileName] [varchar](max) NOT NULL,
	[ChunkSize] [float] NOT NULL,
	[ChunkId] [int] NOT NULL,
	[FileFK] [int] NOT NULL,
 CONSTRAINT [PK_TempFiles] PRIMARY KEY CLUSTERED 
(
	[TempFilePK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[Files] ADD  CONSTRAINT [DF_Files_IsComplete]  DEFAULT ((0)) FOR [IsComplete]

ALTER TABLE [dbo].[Files] ADD  CONSTRAINT [DF_Files_FileID]  DEFAULT (newid()) FOR [FileID]

ALTER TABLE [dbo].[TempFiles]  WITH CHECK ADD  CONSTRAINT [FK_TempFiles_Files] FOREIGN KEY([FileFK])
REFERENCES [dbo].[Files] ([FilePK])

ALTER TABLE [dbo].[TempFiles] CHECK CONSTRAINT [FK_TempFiles_Files]

USE [master]

ALTER DATABASE [FileUploader] SET  READ_WRITE 

